version: '3.8'
services:
  # PHP + Apache
  php:
    image: yiisoftware/yii2-php:8.4-apache
    container_name: yii2-books-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      DB_DSN: mysql:host=db;dbname=${DB_NAME}
      DB_USER: ${DB_ROOT_USER}
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
  # MySQL
  db:
    image: mysql:8.0
    container_name: yii2-books-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/my
# Том для хранения данных MySQL
volumes:
  mysql-data: